"""
AIRA Core Data Models
Canonical Event Representation, Graph Entities, Hypotheses, and Incident Dossier Schemas.
"""

from __future__ import annotations
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class EventType(str, Enum):
    PROCESS_CREATE = "PROCESS_CREATE"
    PROCESS_TERMINATE = "PROCESS_TERMINATE"
    PROCESS_ACCESS = "PROCESS_ACCESS"
    IMAGE_LOAD = "IMAGE_LOAD"
    NETWORK_CONNECT = "NETWORK_CONNECT"
    FILE_CREATE = "FILE_CREATE"
    FILE_DELETE = "FILE_DELETE"
    FILE_MODIFY = "FILE_MODIFY"
    REGISTRY_SET = "REGISTRY_SET"
    LOGON = "LOGON"
    ALERT = "ALERT"
    GENERIC = "GENERIC"


class ProcessEntity(BaseModel):
    pid: int
    image: str
    command_line: Optional[str] = ""
    parent_pid: Optional[int] = None
    parent_image: Optional[str] = ""
    parent_command_line: Optional[str] = ""
    user: Optional[str] = ""
    hashes: Optional[Dict[str, str]] = Field(default_factory=dict)
    guid: Optional[str] = None


class NetworkEntity(BaseModel):
    src_ip: str
    src_port: int
    dst_ip: str
    dst_port: int
    protocol: str = "tcp"
    dns_query: Optional[str] = None


class FileEntity(BaseModel):
    path: str
    hashes: Optional[Dict[str, str]] = Field(default_factory=dict)
    action: Optional[str] = "created"


class RegistryEntity(BaseModel):
    key_path: str
    value_name: Optional[str] = None
    value_data: Optional[str] = None


class CanonicalEvent(BaseModel):
    """
    Standardized event format ingested across Sysmon, Windows Security EVTX, and Zeek.
    """
    record_id: str
    timestamp: datetime
    host: str
    user: str
    source_channel: str = "Sysmon"
    event_id: int
    event_type: EventType
    process: Optional[ProcessEntity] = None
    network: Optional[NetworkEntity] = None
    file: Optional[FileEntity] = None
    registry: Optional[RegistryEntity] = None
    raw_payload: Optional[Dict[str, Any]] = Field(default_factory=dict)


class MitreTechnique(BaseModel):
    id: str  # e.g., T1059.001
    name: str  # e.g., PowerShell
    tactic: str  # e.g., Execution
    description: str
    confidence: float = Field(ge=0.0, le=1.0)


class Hypothesis(BaseModel):
    """
    Evidence-grounded hypothesis generated by the reasoning engine.
    """
    hypothesis_id: str
    title: str
    description: str
    mitre_techniques: List[MitreTechnique] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_events: List[str] = Field(default_factory=list)  # Record IDs
    contradicting_events: List[str] = Field(default_factory=list)
    missing_evidence: List[str] = Field(default_factory=list)
    verdict: str = "SUSPICIOUS"  # BENIGN, SUSPICIOUS, MALICIOUS
    bayesian_posterior: Optional[float] = None
    bayesian_likelihood_ratio: Optional[float] = None
    bayesian_trajectory: Optional[List[Dict[str, Any]]] = Field(default_factory=list)
    bayesian_verdict: Optional[str] = None


class TimelineEntry(BaseModel):
    timestamp: datetime
    stage: str
    actor: str
    action: str
    target: str
    evidence_record_id: str
    mitre_id: Optional[str] = None
    severity: str = "INFO"  # INFO, LOW, MEDIUM, HIGH, CRITICAL


class RecommendedAction(BaseModel):
    action_type: str  # ISOLATE_HOST, KILL_PROCESS, BLOCK_IP, QUARANTINE_FILE, RESET_CREDENTIALS
    priority: str  # IMMEDIATE, HIGH, MEDIUM, LOW
    target: str
    rationale: str
    requires_approval: bool = True


class IncidentDossier(BaseModel):
    """
    Complete output generated by AIRA for human analyst review.
    """
    incident_id: str
    title: str
    severity: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    affected_hosts: List[str]
    affected_users: List[str]
    executive_summary: str
    hypotheses: List[Hypothesis]
    timeline: List[TimelineEntry]
    attack_graph_summary: Dict[str, Any]
    recommended_actions: List[RecommendedAction]
    analyst_decision: Optional[str] = "PENDING_REVIEW"
